name: Auto Assign Issue to project
on: [issues]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: assing issue to project
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project_path: 'https://github.com/users/AlexisMateo/projects/2'
    


